/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_leo_device_root_RootNative */

extern "C" {
#include <jni.h>

JNIEXPORT jint
JNICALL Java_com_leo_device_root_RootNative_checkForRoot
        (JNIEnv *, jobject, jobjectArray);


JNIEXPORT void JNICALL Java_com_leo_device_root_RootNative_setLogDebugMessages
        (JNIEnv *, jobject, jboolean);

}
